language: go

matrix:
  fast_finish: true
  include:
    - go: 1.11.x
      env: GO111MODULE=on
    - go: 1.12.x
      env: GO111MODULE=on
    - go: master
      env: GO111MODULE=on

git:
  depth: 10

before_install:
  - if [[ "${GO111MODULE}" = "on" ]]; then mkdir "${HOME}/go"; export GOPATH="${HOME}/go"; fi

install:
  - make mod

go_import_path: github.com/saltbo/gofrobot

script:
  - make
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)