services:
  gofbot:
    build:
      context: .
      dockerfile: Dockerfile
#    image: bonaysoft/gofbot:latest
    command:
      - --adapter
      - telegram
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data