apiVersion: v1alpha1
kind: Message
metadata:
  name: gl-lark-note
spec:
  selector:
    matchLabels:
      chatProvider: lark
      event_type: note
  reply:
    json:
      header:
        title:
          content: "收到一条给 {{ .object_attributes.noteable_type }} 的评论"
          tag: plain_text
      elements:
        - tag: div
          text:
            content: |-
              项目：{{ .project.name }}
              内容：{{ larkAtTransform4All .object_attributes.note `@foxmail.com` }}
              创建人：{{ .user.name }}
              创建时间：{{ .object_attributes.created_at }}
            tag: lark_md
        - tag: action
          actions:
            - tag: button
              text:
                content: "查看"
                tag: lark_md
              url: "{{ .object_attributes.url }}"
              type: default