name: build

on:
  push:
    branches:
      - develop
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: MakeTest
        uses: saltbo/actions/make-test@master
        with:
          language: golang
          context: .
