name: build

on:
  push:
    branches:
      - develop
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: saltbo/actions/make-test@master
        with:
          language: golang
          context: .
