name: build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Image build and release
        uses: saltbo/actions/release-image@master
        with:
          project-name: gofbot
          language: golang
          context: .
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tags: ghcr.io/bonaysoft/gofbot:latest, ghcr.io/bonaysoft/gofbot:${{ github.ref_name }}
